USE currensee;

ALTER TABLE users
  ADD COLUMN role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER',
  ADD COLUMN status ENUM('ACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  ADD INDEX idx_users_status (status);

